<div id='<?php print $this->baseStyleName; ?>' class='block block-<?php print $this->baseStyleName; ?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-content'>
        <div class='title'>
            <div class='title-bg'></div>
            <div class='title-text'><?php print t('Share your cheerful');?>&nbsp;&nbsp;&nbsp;<a href='<?php print url('book/61');?>'>&gt;&gt;&gt;</a></div>
        </div>
        <div class='clearfix'></div>
    </div>
</div>