<div id='<?php print $this->baseStyleName; ?>' class='block block-<?php print $this->baseStyleName; ?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-title'></div>
    <div class='block-content'>
        <div class='title'>
            <div class='title-bg'></div>
            <div class='title-text'><?php print t('How to use Lasooo?');?></div>
        </div>
        <div class='icons'>
           <span><a href='<?php print url('book/115')?>'>Join</a></span>
            <span><a href='<?php print url('book/61')?>'>Share</a></span>
            <span><a href='<?php print url('book/4')?>'>Discovery</a></span>
        </div>
        <div class='clearfix'></div>
    </div>
</div>