<div id='<?php print $this->baseStyleName;?>' class='block block-<?php print $this->baseStyleName;?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-title'></div>
    <div class='block-content'>
        <div class='period'>第1期</div>
        <div class='created'>活动创建于：<?php print date("Y年m月d日", $this->node->created);?></div>
        <div class='clearfix'></div>
    </div>
</div>