<div id='<?php print strtolower($this->viewName)?>' class='block block-<?php print strtolower($this->viewName);?> feature-<?php print $this->view['feature'];?>'>
    <div class='block-title'></div>
    <div class='block-content'>
        <img src='<?php print file_create_url('public://views/lasooo/2992964_121349008_2.jpg');?>' width='960' title='Join lasooo, Enjoy your life and travel time.'/>
        <div class='clearfix'></div>
    </div>
</div>