<div id='<?php print strtolower($this->viewName)?>' class='block block-<?php print strtolower($this->viewName);?> feature-<?php print $this->view['feature'];?>'>
    <div class='block-title'></div>
    <div class='block-content'>
        <span class='title'><?php print t('Recommand lasooo to your friends for share experience and cheerful time');?></span>
        <div class='clearfix'></div>
    </div>
</div>