<div id='<?php print $this->baseStyleName;?>' class='block block-<?php print $this->baseStyleName;?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-title'></div>
    <div class='block-content slideContainer clearfix'>
        <div class='frontpage-photo node-drawingboard node'><img src='/misc/xf1996/frontpage.jpg' /></div>
    </div>
</div>