<div id='<?php print $this->baseStyleName;?>' class='block block-<?php print $this->baseStyleName;?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-title'><img src='/misc/xf1996/block-title-hdsp.jpg' /></div>
    <div class='block-content clearfix'>
        <?php print render($this->buildNodes);?>
    </div>
</div>
