<div class='block block-member-homepage block-member-homepage-card'>
<div class='block-title'><img src='/misc/xf1996/block-title-xfcard.jpg' /></div>
<div class='block-content'><img width='600' src='/misc/xf1996/member-card-01.png' /></div>
</div>
<div class='block block-member-homepage'>
<div class='block-content'>
<br /></br />
<div class='content-section'>
    <div class='section-title'><img src='/misc/xf1996/block-title-sygz.jpg' /></div>
<p>
一、总则：<br />
1、南京先锋书店VIP卡为先锋书店会员卡；<br />
2、VIP卡功能： 持卡贵宾在先锋书店各连锁店消费（活动期间除外、杂志、创意产品除外）， 均可享受8折、8.5折、9折优惠。<br />
</p>
<p>
二、入会方式：<br />
新会员填写入会资料交纳一定年费，即可申领9折至8折不定的会员卡。<br />
</p>
<div class='clearfix'></div>
</div>
<div class='content-section'>
<div class='section-title'><img src='/misc/xf1996/block-title-sqgz.jpg' /></div>

<p>
1、意愿申办的顾客，都可到南京先锋书店各连锁店收银台办理申办手续；<br />
2、申办顾客须按规定详实地填写申请表（“顾客必填栏”由顾客填写，“内部填写”由本店工作人员填写）；<br />
ａ、顾客的姓名、性别、手机号码（或者电话号码）、工作单位（若是学生，填写学校名称）、通讯地址、申请日期六项是必填栏。（具体填写参见样表）<br />
b、顾客务必用楷体登记相关资料，因登记不清楚、资料有误而导致卡未及时开通的顾客需承担相应责任，若出现上述情况，请顾客携本卡到客服中心核对相关资料开通此卡，办理时间：每周一～周五（节假日除外），上午10：00～下午5：00；<br />
c、门店收银员对顾客登记的申请资料负有审核的义务，审核无误后登记有关信息发放会员卡，顾客在确认审核无误后方可离开。</div>
</p>
<div class='clearfix'></div>
</div>
</div>
<div class='block block-member-homepage block-member-homepage-card'>
<div class='block-title'><img src='/misc/xf1996/block-title-xfcardwithdollor.jpg' /></div>
<div class='block-content'><img width='600' src='/misc/xf1996/member-card-02.png' /></div>
</div>