<div id='<?php print $this->baseStyleName; ?>' class='block block-<?php print $this->baseStyleName; ?> block-<?php print $this->baseStyleName;?>-<?php print $this->view['private_key'];?> feature-<?php print $this->feature;?>'>
    <div class='block-title'></div>
    <div class='block-content'>
        <div class='title'>
            <div class='title-bg'></div>
            <div class='title-text'><a href='<?php print url('book/62');?>'><?php print t('Learning lasooo public welfare plan');?></a></div>
        </div>
        <div class='desc'>
            <?php print t('Help more people to learning nature and healthy life style.');?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>